FROM postgres:14.12

# Set PostgreSQL credentials
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=123123

# Copy task-specific initialization script
COPY environment/init-db.sh /docker-entrypoint-initdb.d/init-db.sh

# Copy task-specific database dumps
COPY environment/db_assets /docker-entrypoint-initdb.d/db_assets

# Set permissions
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh \
    && chmod -R 755 /docker-entrypoint-initdb.d/db_assets
